### PR TITLE
reconciliation of publication year

### PR DESCRIPTION
**Pull request by wdyrka**
Dear Editors,

we have found that the time passed between the conference (2018) and publication (2019) has caused some mess regarding discrepancies between dates on and in the papers, on the website and in bibliographic records. This is an attempt to reconcile the dates. Briefly, the publication year is everywhere set to 2019, while the conference date is added to the booktitle to avoid confusion.

Kind regards,
Witold Dyrka

### CODE REVIEW

**Review by lawrennd — APPROVED** [review]
Thanks for this, I'm approving now, but it will be worth checking the links and bib files etc to make sure the changes propagate in the way you're expecting.

**Comment by wdyrka** [comment]
Dear Neil,

what shall I do in order to this approved pull request be merged in the
official repository?

As far as I managed to check locally, the changes propagates correctly.

Best regards,
Witold

pt., 15 lut 2019 o 22:09 użytkownik Neil Lawrence <notifications@github.com>
napisał:

**Comment by lawrennd** [comment]
Apologies, I think I meant to merge when I approved but forgot, have done now.

**Comment by wdyrka** [comment]
Many thanks,
Witold

pon., 25 mar 2019 o 22:42 użytkownik Neil Lawrence <notifications@github.com>
napisał:

**Pull request merged**
